ProductionManagement.WebUI/Controllers/HomeController.cs
using ProductManagement.DomainModel.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManagement.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private IDataRepository repository;
        public HomeController(IDataRepository repo)
        {
            repository = repo;
        }
        public ViewResult Index()
        {
            return View(repository.Productions);
        }

    }
}

ProductionManagement.WebUI/Controllers/ProductionController.cs
using ProductionManagement.WebUI.Infrastructure;
using ProductManagement.DomainModel.Abstract;
using ProductManagement.DomainModel.ProductionData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManagement.WebUI.Controllers
{
    public class ProductionController : Controller
    {
        private IDataRepository repository;

        public ProductionController(IDataRepository repo)
        {
            repository = repo;
        }

        public ActionResult AddNewSingle()
        {
            SingleProduction production = new SingleProduction();
            return View(production);
        }

        [HttpPost]
        [OutOfRangeException]
        public ActionResult AddNewSingle(SingleProduction production)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduction(production);
                return RedirectToAction("Index", "Home");
            }
            return View(production);
        }

        public ActionResult AddNewRange()
        {
            RangeProduction production = new RangeProduction();
            return View(production);
        }

        [HttpPost]
        [OutOfRangeException]
        public ActionResult AddNewRange(RangeProduction production)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduction(production);
                return RedirectToAction("Index", "Home");
            }
            return View(production);
        }

        public ActionResult Edit(int? productionId)
        {
            if (productionId.HasValue)
            {
                var production = repository.Productions.FirstOrDefault(x => x.ProductionId == productionId.Value);
                if (production == null)
                    return View("Error", "Не найден объект для редактирования");

                if (production is SingleProduction)
                    return View("AddNewSingle", production);
                else return View("AddNewRange", production);
            }
            else return View("Error", "Не найден объект для редактирования");
        }

        [HttpPost]
        [DeleteExcepton]
        public ActionResult Delete(int productionId)
        {
            repository.DeleteProduction(productionId);
            return RedirectToAction("Index", "Home");
        }
    }
}

ProductionManagement.WebUI/Views/Home/Index.cshtml
@using System.Linq;
@model IQueryable<ProductManagement.DomainModel.Abstract.AbstractProduction>

@{
    ViewBag.Title = "Производство";
}

<h2>Производство</h2>
<table>
    <thead>
        <tr>
            <th>Номер п.п.</th>
            <th>Дата производства</th>
            <th>Номера продукции</th>
            <th></th>
        </tr>
    </thead>
    @foreach (var prod in Model)
    {
        <tr>
            <td>@prod.ProductionId</td>
            <td>@prod.ProductionDate</td>
            <td>@Html.ActionLink(prod.ToString(), "Edit", "Production", new { prod.ProductionId }, new { @class = "EditLink" })</td>
            <td>
                @using(Html.BeginForm("Delete", "Production"))
                {
                    @Html.Hidden("productionId", prod.ProductionId);
                    <input type="submit" value="Удалить" onclick="return confirm('Вы действительно хотите удалить производство с номером(ами)  @prod.ToString() ?')" />
                }
        </tr>
    }
</table>

<div class="actions">
    @Html.ActionLink("Добавить новое производство (одиночное)", "AddNewSingle", "Production")
    @Html.ActionLink("Добавить новое производство (диапазон)", "AddNewRange", "Production")
</div>

ProductionManagement.WebUI/Views/Production/AddNewRange.cshtml
@model ProductManagement.DomainModel.ProductionData.RangeProduction

@{
    ViewBag.Title = "AddNewRange";
}

<h2>Создание/редактирование производства (Диапазон элементов)</h2>

@using (Html.BeginForm("AddNewRange", "Production"))
{
    <div class="dataLabel">@Html.DisplayNameFor(x => x.ProductionDate)</div>
    <div class="dataValue">@Html.EditorFor(x => x.ProductionDate)</div>
    <div class="dataLabel">@Html.DisplayNameFor(x => x.StartNumber)</div>
    <div class="dataValue">@Html.EditorFor(x => x.StartNumber)</div>
    <div class="dataLabel">@Html.DisplayNameFor(x => x.EndNumber)</div>
    <div class="dataValue">@Html.EditorFor(x => x.EndNumber)</div>
    <div>@Html.EditorFor(x => x.ProductionId)</div>

    <div class="actions">
        <input type="submit" value="Сохранить" />
        <input type="reset" value="Очистить" />
        <input type="button" value="Отмена" onclick="window.location.href = '@Url.Action("Index", "Home")'" />
    </div>
}

ProductionManagement.WebUI/Views/Production/AddNewSingle.cshtml
@model ProductManagement.DomainModel.ProductionData.SingleProduction

@{
    ViewBag.Title = "AddNew";
}

<h2>Создание/редактирование производства (один элемент)</h2>


@using (Html.BeginForm("AddNewSingle", "Production"))
{
   
    <div class="dataLabel">@Html.DisplayNameFor(x => x.ProductionDate)</div>
    <div class="dataValue">@Html.EditorFor(x => x.ProductionDate)</div>
    <div class="dataLabel">@Html.DisplayNameFor(x => x.ProductNumber)</div>
    <div class="dataValue">@Html.EditorFor(x => x.ProductNumber)</div>
    <div>@Html.EditorFor(x => x.ProductionId)</div>
    
    <div class="actions">
        <input type="submit" value="Сохранить"/>
        <input type="reset" value="Очистить" />
        <input type="button" value="Отмена" onclick="window.location.href = '@Url.Action("Index", "Home")'" />
    </div>
}

ProductionManagement.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>